encoding: utf-8
# Site
name: '3D NA VEIA'
description: 'Olá! Me chamo Eduardo Maia, sejam todos bem vindos ao 3D NA VEIA.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/gdscript-basico-3.2'
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /blog/:year/:month/:day/:title:output_ext

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: :compressed


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, .sass-cache]